export interface Theme {
  id: string;
  name: string;
  vars: Record<string, string>;
}

export const themes: Theme[] = [
  {
    id: "one-dark",
    name: "One Dark",
    vars: {
      "--bg-primary": "#282c34",
      "--bg-secondary": "#2e323c",
      "--bg-tertiary": "#23272e",
      "--bg-elevated": "#353b45",
      "--text-primary": "#dcdfe4",
      "--text-secondary": "#9da5b4",
      "--text-muted": "#5c6370",
      "--accent-blue": "#61afef",
      "--accent-green": "#98c379",
      "--accent-yellow": "#e5c07b",
      "--accent-red": "#e06c75",
      "--accent-purple": "#c678dd",
      "--accent-cyan": "#56b6c2",
      "--border-color": "#3e4452",
      "--border-subtle": "#343a46",
      "--tab-active": "#282c34",
      "--tab-inactive": "#23272e",
      "--hover-bg": "rgba(255, 255, 255, 0.06)",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    vars: {
      "--bg-primary": "#282a36",
      "--bg-secondary": "#2d2f3d",
      "--bg-tertiary": "#21222c",
      "--bg-elevated": "#383a4a",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#bfbfbf",
      "--text-muted": "#6272a4",
      "--accent-blue": "#8be9fd",
      "--accent-green": "#50fa7b",
      "--accent-yellow": "#f1fa8c",
      "--accent-red": "#ff5555",
      "--accent-purple": "#bd93f9",
      "--accent-cyan": "#8be9fd",
      "--border-color": "#44475a",
      "--border-subtle": "#393b4a",
      "--tab-active": "#282a36",
      "--tab-inactive": "#21222c",
      "--hover-bg": "rgba(255, 255, 255, 0.07)",
    },
  },
  {
    id: "nord",
    name: "Nord",
    vars: {
      "--bg-primary": "#2e3440",
      "--bg-secondary": "#333947",
      "--bg-tertiary": "#282e3a",
      "--bg-elevated": "#3b4252",
      "--text-primary": "#eceff4",
      "--text-secondary": "#d8dee9",
      "--text-muted": "#616e88",
      "--accent-blue": "#88c0d0",
      "--accent-green": "#a3be8c",
      "--accent-yellow": "#ebcb8b",
      "--accent-red": "#bf616a",
      "--accent-purple": "#b48ead",
      "--accent-cyan": "#88c0d0",
      "--border-color": "#434c5e",
      "--border-subtle": "#3b4252",
      "--tab-active": "#2e3440",
      "--tab-inactive": "#282e3a",
      "--hover-bg": "rgba(255, 255, 255, 0.05)",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    vars: {
      "--bg-primary": "#1a1b26",
      "--bg-secondary": "#1f2030",
      "--bg-tertiary": "#16161e",
      "--bg-elevated": "#292e42",
      "--text-primary": "#c0caf5",
      "--text-secondary": "#a9b1d6",
      "--text-muted": "#565f89",
      "--accent-blue": "#7aa2f7",
      "--accent-green": "#9ece6a",
      "--accent-yellow": "#e0af68",
      "--accent-red": "#f7768e",
      "--accent-purple": "#bb9af7",
      "--accent-cyan": "#7dcfff",
      "--border-color": "#2f3549",
      "--border-subtle": "#282940",
      "--tab-active": "#1a1b26",
      "--tab-inactive": "#16161e",
      "--hover-bg": "rgba(255, 255, 255, 0.05)",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    vars: {
      "--bg-primary": "#1e1e2e",
      "--bg-secondary": "#232336",
      "--bg-tertiary": "#181825",
      "--bg-elevated": "#313244",
      "--text-primary": "#cdd6f4",
      "--text-secondary": "#bac2de",
      "--text-muted": "#585b70",
      "--accent-blue": "#89b4fa",
      "--accent-green": "#a6e3a1",
      "--accent-yellow": "#f9e2af",
      "--accent-red": "#f38ba8",
      "--accent-purple": "#cba6f7",
      "--accent-cyan": "#94e2d5",
      "--border-color": "#45475a",
      "--border-subtle": "#383850",
      "--tab-active": "#1e1e2e",
      "--tab-inactive": "#181825",
      "--hover-bg": "rgba(255, 255, 255, 0.05)",
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    vars: {
      "--bg-primary": "#0d1117",
      "--bg-secondary": "#131920",
      "--bg-tertiary": "#090c10",
      "--bg-elevated": "#1c2128",
      "--text-primary": "#e6edf3",
      "--text-secondary": "#b1bac4",
      "--text-muted": "#545d68",
      "--accent-blue": "#58a6ff",
      "--accent-green": "#3fb950",
      "--accent-yellow": "#d29922",
      "--accent-red": "#f85149",
      "--accent-purple": "#bc8cff",
      "--accent-cyan": "#39d2c0",
      "--border-color": "#30363d",
      "--border-subtle": "#262c34",
      "--tab-active": "#0d1117",
      "--tab-inactive": "#090c10",
      "--hover-bg": "rgba(255, 255, 255, 0.04)",
    },
  },
];

export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) ?? themes[0];
}

export function getXtermTheme(theme: Theme): Record<string, string> {
  return {
    background: theme.vars["--bg-primary"],
    foreground: theme.vars["--text-primary"],
    cursor: theme.vars["--text-primary"],
    selectionBackground: theme.vars["--bg-elevated"],
    black: theme.vars["--bg-tertiary"],
    red: theme.vars["--accent-red"],
    green: theme.vars["--accent-green"],
    yellow: theme.vars["--accent-yellow"],
    blue: theme.vars["--accent-blue"],
    magenta: theme.vars["--accent-purple"],
    cyan: theme.vars["--accent-cyan"],
    white: theme.vars["--text-primary"],
    brightBlack: theme.vars["--text-muted"],
    brightRed: theme.vars["--accent-red"],
    brightGreen: theme.vars["--accent-green"],
    brightYellow: theme.vars["--accent-yellow"],
    brightBlue: theme.vars["--accent-blue"],
    brightMagenta: theme.vars["--accent-purple"],
    brightCyan: theme.vars["--accent-cyan"],
    brightWhite: "#ffffff",
  };
}
